#!/bin/bash
export DISPLAY=:0 2>&1>/dev/null
DRIVER=$(/opt/ethos/sbin/ethos-readconf driver)
case "$DRIVER" in
  fglrx )
    /usr/bin/aticonfig --od-enable
    /usr/bin/aticonfig --odsc=800,0 --adapter="$1"
    sleep 2
    /usr/local/bin/atitweak -p 0 -A "$1"
    sleep 2
    /usr/local/bin/atitweak -f 100
  ;;
  amdgpu )
    GPUCOUNT=$(($(cat /var/run/ethos/gpucount.file) - 1))
    for i in $(seq 0 $GPUCOUNT); do
      HWMONDIR=$(echo /sys/class/drm/card$i/device/hwmon/* | grep -Poi "(?<=hwmon)(\d+)") 
      echo 1 > /sys/class/drm/card$i/device/hwmon/hwmon"$HWMONDIR"/pwm1_enable
      echo "255" > /sys/class/drm/card$i/device/hwmon/hwmon"$HWMONDIR"/pwm1
    done
  ;; 
  nvidia )
	#Set to 1 watt above minimum, because sometimes minimum will not apply
	MINWATTS=( $(cat /var/run/ethos/watt_min.file | sed -e 's/\.[0-9][0-9]//g') )
	MINWATTS[$1]="$(( ${MINWATTS[$1]}+1))"
	WATTS=($(/opt/ethos/sbin/ethos-readdata watts | sed -e 's/\.[0-9][0-9]//g'))
	if [ "$WATTS" -gt "${MINWATTS[$1]}" ];then
		/usr/bin/sudo /usr/bin/nvidia-smi -i "$1" -pl "${MINWATTS[$1]}"
	fi
	/usr/bin/nvidia-settings -a [gpu:"$1"]/GPUFanControlState=1 -a [fan:"$1"]/GPUTargetFanSpeed=100		
  ;;
esac
